config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # config/routes.rb

#   devise_for :users, controllers: {
#     sessions: 'users/sessions'
#     # Add other controllers here if you generated them and want to customize
#   }
#     # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

#   # Defines the root path route ("/")
#   # root "articles#index"
# end
# Rails.application.routes.draw do
  devise_for :pub_owners
  devise_for :users, controllers: {registrations: "users/registrations"}
  resources :pub_profiles do
    resources :menus, :offers
  end
  resources :menus
  resources :offers
  resources :bookings
 
  # Additional custom routes or resources can be added here...

  # Define a root route
  root 'welcome#index'
end

app/models/menu.rb
class Menu < ApplicationRecord
    belongs_to :pub_profile
    enum item_type: { food: 0, alcohol: 1 }
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
      def new
        @menu = Menu.new
      end
       
      def index
        @menus = Menu.all
      end

      def show
        @menu = Menu.find(params[:id])
      end

      def create
        @pub_profile = PubProfile.find(params[:pub_profile_id])
        @menu = @pub_profile.menus.create(menu_params)
        redirect_to pub_profile_path(@pub_profile)
      end
    private

      def menu_params
        params.require(:menu).permit(:name, :price, :item_type)
      end
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/index.html.erb
<h1>Listing Menus</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Item Type</th>
    <th>Pub</th>
    </tr>

  <% @menus.each do |menu| %>
    <tr>
      <td><%= menu.name %></td>
      <td><%= menu.price %></td>
      <td><%= menu.item_type %></td>
      <td><%= menu.pub_profile.name %></td>
      <td><%= link_to 'Show', menu_path(menu) %></td>
    </tr>
  <% end %>
</table>

app/views/menus/new.html.erb
<%= form_with model: @menu, local: true do |form| %>
    <p>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
    </p>
     
    <p>
      <%= form.label :price %><br>
      <%= form.text_area :price %>
    </p>
     
    <p>
      <%= form.label :item_type %><br>
      <%= form.text_field :item_type %>
    </p>

    <p>
      <%= form.label :pub_profile_id %><br>
      <%= form.text_field :pub_profile_id %>
    </p>

    <p>
      <%= form.submit %>
    </p>
  <% end %>
  

app/views/menus/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @menu.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @menu.price %>
</p>

<p>
  <strong>Item Type:</strong>
  <%= @menu.item_type %>
</p>

<p>
  <strong>Pub:</strong>
  <%= @menu.pub_profile.name %>
</p>