config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # config/routes.rb

#   devise_for :users, controllers: {
#     sessions: 'users/sessions'
#     # Add other controllers here if you generated them and want to customize
#   }
#     # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

#   # Defines the root path route ("/")
#   # root "articles#index"
# end
# Rails.application.routes.draw do
  devise_for :pub_owners
  devise_for :users, controllers: {registrations: "users/registrations"}
  resources :pub_profiles do
    resources :menus, :offers
  end
  resources :menus
  resources :offers
  resources :bookings
 
  # Additional custom routes or resources can be added here...

  # Define a root route
  root 'welcome#index'
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :user
    belongs_to :pub_profile
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    # before_action :authenticate_user!, only: [:create]
      
        def index
            if current_user
              @bookings = Booking.where(user_id: current_user.id)
            else
              @pub_profile = current_pub_owner.pub_profiles
              @bookings = Booking.where(pub_profile_id: @pub_profile.ids)
            end
        end
    
        def create
          @user = current_user
          @pub_profile = PubProfile.find(params[:pub_profile_id])
          @booking = Booking.create(user: @user, pub_profile: @pub_profile, check_in_time: Time.now)
          if @booking.save
            flash[:notice] = "Booking created successfully."
            redirect_to pub_profile_path(@pub_profile) 
          else
            flash[:alert] = "Failed to create a booking."
            redirect_to pub_profiles_path 
          end
        end
    
        def show
          @booking = Booking.find(params[:id])
        end

        def edit
          @booking = Booking.find(params[:id])
        end

        def update
          if current_pub_owner
            @booking = Booking.find(params[:id])
            if @booking.update(booking_params)
              flash[:notice] = "Booking updated successfully."
              redirect_to bookings_path
            else
              flash[:alert] = "Failed to update booking."
              render :edit
            end
          end
        end
        
        private
        
        def booking_params
          params.require(:booking).permit(:check_out_time, :number_of_people)
        end
        
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/edit.html.erb
<h1>Edit Booking</h1>
 
<%= form_with(model: @booking) do |form| %>
 
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@booking.errors.count, "error") %> prohibited
        this booking from being saved:
      </h2>
      <ul>
        <% @booking.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
  <%= form.label :check_out_time %><br>
  <%= form.text_field :check_out_time %>
</p>

<p>
<%= form.label :number_of_people %><br>
<%= form.text_field :number_of_people %>
</p>
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<h1 class="text-center">List of Bookings</h1>

<div class="table-responsive">
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th scope="col">User</th>
        <th scope="col">Registered Pub</th>
      </tr>
    </thead>
    <tbody>
      <% @bookings.each do |booking| %>
        <tr>
          <td><%= booking.user.email %></td>
          <td><%= booking.pub_profile.name %></td>
          <td>
            <% if current_pub_owner %>
              <%= link_to 'Edit', edit_booking_path(booking), class: 'btn btn-primary btn-sm' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>