config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # config/routes.rb

#   devise_for :users, controllers: {
#     sessions: 'users/sessions'
#     # Add other controllers here if you generated them and want to customize
#   }
#     # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

#   # Defines the root path route ("/")
#   # root "articles#index"
# end
# Rails.application.routes.draw do
  devise_for :pub_owners
  devise_for :users, controllers: {registrations: "users/registrations"}
  resources :pub_profiles do
    resources :menus, :offers
  end
  resources :menus
  resources :offers
  resources :bookings
 
  # Additional custom routes or resources can be added here...

  # Define a root route
  root 'welcome#index'
end

app/models/pub_profile.rb
class PubProfile < ApplicationRecord
    belongs_to :pub_owner
    has_many :menus
    has_many :offers
    has_many :bookings
    has_many :users, through: :bookings
        def current_number_of_people
           current_time = Time.now
           active_bookings = bookings.where('check_in_time <= ? AND (check_out_time IS NULL OR check_out_time >= ?)', current_time, current_time)
           total_people = active_bookings.sum(:number_of_people)
        end
end

app/controllers/pub_profiles_controller.rb
class PubProfilesController < ApplicationController
  before_action :authenticate_pub_owner!, only: [:create]
  
    def new
      @pub_profile = PubProfile.new
    end

    def index 
      if current_pub_owner
        @pub_profiles = current_pub_owner.pub_profiles
      else
      @pub_profiles = PubProfile.all
      end
    end

    def show
      @pub_profile = PubProfile.find(params[:id])
      @current_number_of_people = @pub_profile.current_number_of_people
    end

    def create
      @pub_profile = current_pub_owner.pub_profiles.build(pub_profile_params)
  
      if @pub_profile.save
        redirect_to pub_profiles_path, notice: 'Pub Profile was successfully created.'
      else
        render :new
      end
    end
  
    private
  
    def pub_profile_params
      params.require(:pub_profile).permit(:name, :description, :location, :capacity, :is_smoking_allowed, :average_rating)
    end
  end

app/helpers/pub_profiles_helper.rb
module PubProfilesHelper
end

app/views/pub_profiles/index.html.erb
<table class="table caption-top">
<h1  class="text-danger"><center>List Of Pubs</center></h1>
  <thead>
    <tr>
      <th scope="col">Serial no.</th>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="col">Location</th>
      <th scope="col">Capacity</th>
      <th scope="col">Current No. Of People</th>
      <th scope="col">Smoking Allowed</th>
      <th scope="col">Average Rating</th>
      <th scope="col">Show</th>
    </tr>
  </thead>
  <tbody>
    <% @pub_profiles.each_with_index do |pub_profile, index| %>
      <tr>
        <th scope="row"><%= index + 1 %></th>
        <td><%= pub_profile.name %></td>
        <td><%= pub_profile.description %></td>
        <td><%= pub_profile.location %></td>
        <td><%= pub_profile.capacity %></td>
        <td><%= pub_profile.current_number_of_people %></td>
        <td><%= pub_profile.is_smoking_allowed ? 'Yes' : 'No' %></td>
        <td><%= pub_profile.average_rating %></td>
        <td><%= link_to 'Show', pub_profile_path(pub_profile),class: "btn btn-warning"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pub_profiles/new.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
    <h1> Pub Profile </h1>
      <%= form_with model: @pub_profile, local: true, html: { class: 'form-edit-pub-profile' } do |form| %>
        <div class="form-group">
          <%= form.label :name %><br>
          <%= form.text_field :name, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= form.label :description %><br>
          <%= form.text_area :description, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= form.label :location %><br>
          <%= form.text_field :location, class: 'form-control' %>
        </div>
      
        <div class="form-group">
          <%= form.label :capacity %><br>
          <%= form.number_field :capacity, class: 'form-control' %>
        </div>
      
        <div class="form-group">
          <%= form.label :is_smoking_allowed %><br>
          <%= form.check_box :is_smoking_allowed, class: 'form-check-input' %>
        </div>
      
        <div class="form-group">
          <%= form.label :average_rating %><br>
          <%= form.number_field :average_rating, step: 0.01, class: 'form-control' %>
        </div>
      
        <div class="form-group">
          <%= form.submit "Create Pub Profile", class: 'btn btn-primary btn-block' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pub_profiles/show.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <h2><%= @pub_profile.name %></h2>

      <p>
        <strong>Name:</strong>
        <%= @pub_profile.name %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= @pub_profile.description %>
      </p>

      <p>
        <strong>Location:</strong>
        <%= @pub_profile.location %>
      </p>

      <p>
        <strong>Capacity:</strong>
        <%= @pub_profile.capacity %>
      </p>

      <p>
        <strong>Smoking Allowed:</strong>
        <%= @pub_profile.is_smoking_allowed ? 'Yes' : 'No' %>
      </p>

      <p>
        <strong>Average Rating:</strong>
        <%= @pub_profile.average_rating %>
      </p>

      <p>
        <strong>Current Number Of People:</strong>
        <%= @pub_profile.current_number_of_people %>
      </p>

      <h2>Menus</h2>
      <% @pub_profile.menus.each do |menu| %>
        <p>
          <strong>Name:</strong>
          <%= menu.name %>
        </p>

        <p>
          <strong>Price:</strong>
          <%= menu.price %>
        </p>

        <p>
          <strong>Item Type:</strong>
          <%= menu.item_type %>
        </p>
      <% end %>

      <% if current_pub_owner %>
        <h2>Add a Menu:</h2>
        <%= form_with(model: [ @pub_profile, @pub_profile.menus.build ], local: true, html: { class: 'form-add-menu' }) do |form| %>
          <div class="form-group">
            <%= form.label :name %><br>
            <%= form.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :price %><br>
            <%= form.text_area :price, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :item_type %><br>
            <%= form.text_area :item_type, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.submit "Add Menu", class: 'btn btn-primary btn-block' %>
          </div>
        <% end %>

        <h2>Add an Offer:</h2>
        <%= form_with(model: [ @pub_profile, @pub_profile.offers.build ], local: true, html: { class: 'form-add-offer' }) do |form| %>
          <div class="form-group">
            <%= form.label :name %><br>
            <%= form.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :description %><br>
            <%= form.text_area :description, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :start_date %><br>
            <%= form.text_area :start_date, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.label :end_date %><br>
            <%= form.text_area :end_date, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= form.submit "Add Offer", class: 'btn btn-primary btn-block' %>
          </div>
        <% end %>
      <% end %>

      <%= button_to "Book Pub", bookings_path(pub_profile_id: @pub_profile.id), method: :post, class: "btn btn-success mt-3 book-button" %>
      <%= link_to 'Back', pub_profiles_path, class: 'btn btn-secondary mt-3' %>
    </div>
  </div>
</div>